# Generated by Django 3.1.5 on 2021-01-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210201_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
