# Generated by Django 3.1.5 on 2021-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210201_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reasion',
            field=models.TextField(),
        ),
    ]
